/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashierRouteImport } from './routes/_authenticated/cashier'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as MenuRestaurantIdTableNumberRouteImport } from './routes/menu.$restaurantId.$tableNumber'
import { Route as AuthenticatedDashboardTablesRouteImport } from './routes/_authenticated/dashboard.tables'
import { Route as AuthenticatedDashboardSalesRouteImport } from './routes/_authenticated/dashboard.sales'
import { Route as AuthenticatedDashboardRolesRouteImport } from './routes/_authenticated/dashboard.roles'
import { Route as AuthenticatedDashboardRecapRouteImport } from './routes/_authenticated/dashboard.recap'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPasswordRouteImport } from './routes/_authenticated/dashboard.password'
import { Route as AuthenticatedDashboardOrdersStatsRouteImport } from './routes/_authenticated/dashboard.orders-stats'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMenuRouteImport } from './routes/_authenticated/dashboard.menu'
import { Route as AuthenticatedDashboardInfoRouteImport } from './routes/_authenticated/dashboard.info'
import { Route as AuthenticatedDashboardDailyReportRouteImport } from './routes/_authenticated/dashboard.daily-report'
import { Route as AuthenticatedDashboardAssistanceRouteImport } from './routes/_authenticated/dashboard.assistance'
import { Route as AuthenticatedDashboardAppearanceRouteImport } from './routes/_authenticated/dashboard.appearance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashierRoute = AuthenticatedCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const MenuRestaurantIdTableNumberRoute =
  MenuRestaurantIdTableNumberRouteImport.update({
    id: '/menu/$restaurantId/$tableNumber',
    path: '/menu/$restaurantId/$tableNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardTablesRoute =
  AuthenticatedDashboardTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSalesRoute =
  AuthenticatedDashboardSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRolesRoute =
  AuthenticatedDashboardRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRecapRoute =
  AuthenticatedDashboardRecapRouteImport.update({
    id: '/recap',
    path: '/recap',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPasswordRoute =
  AuthenticatedDashboardPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersStatsRoute =
  AuthenticatedDashboardOrdersStatsRouteImport.update({
    id: '/orders-stats',
    path: '/orders-stats',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMenuRoute =
  AuthenticatedDashboardMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInfoRoute =
  AuthenticatedDashboardInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDailyReportRoute =
  AuthenticatedDashboardDailyReportRouteImport.update({
    id: '/daily-report',
    path: '/daily-report',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssistanceRoute =
  AuthenticatedDashboardAssistanceRouteImport.update({
    id: '/assistance',
    path: '/assistance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAppearanceRoute =
  AuthenticatedDashboardAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AuthenticatedCashierRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/dashboard/appearance': typeof AuthenticatedDashboardAppearanceRoute
  '/dashboard/assistance': typeof AuthenticatedDashboardAssistanceRoute
  '/dashboard/daily-report': typeof AuthenticatedDashboardDailyReportRoute
  '/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/orders-stats': typeof AuthenticatedDashboardOrdersStatsRoute
  '/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/recap': typeof AuthenticatedDashboardRecapRoute
  '/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/menu/$restaurantId/$tableNumber': typeof MenuRestaurantIdTableNumberRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AuthenticatedCashierRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/dashboard/appearance': typeof AuthenticatedDashboardAppearanceRoute
  '/dashboard/assistance': typeof AuthenticatedDashboardAssistanceRoute
  '/dashboard/daily-report': typeof AuthenticatedDashboardDailyReportRoute
  '/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/orders-stats': typeof AuthenticatedDashboardOrdersStatsRoute
  '/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/recap': typeof AuthenticatedDashboardRecapRoute
  '/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/menu/$restaurantId/$tableNumber': typeof MenuRestaurantIdTableNumberRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cashier': typeof AuthenticatedCashierRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/dashboard/appearance': typeof AuthenticatedDashboardAppearanceRoute
  '/_authenticated/dashboard/assistance': typeof AuthenticatedDashboardAssistanceRoute
  '/_authenticated/dashboard/daily-report': typeof AuthenticatedDashboardDailyReportRoute
  '/_authenticated/dashboard/info': typeof AuthenticatedDashboardInfoRoute
  '/_authenticated/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/orders-stats': typeof AuthenticatedDashboardOrdersStatsRoute
  '/_authenticated/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/recap': typeof AuthenticatedDashboardRecapRoute
  '/_authenticated/dashboard/roles': typeof AuthenticatedDashboardRolesRoute
  '/_authenticated/dashboard/sales': typeof AuthenticatedDashboardSalesRoute
  '/_authenticated/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/menu/$restaurantId/$tableNumber': typeof MenuRestaurantIdTableNumberRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cashier'
    | '/dashboard'
    | '/kitchen'
    | '/dashboard/appearance'
    | '/dashboard/assistance'
    | '/dashboard/daily-report'
    | '/dashboard/info'
    | '/dashboard/menu'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/orders-stats'
    | '/dashboard/password'
    | '/dashboard/profile'
    | '/dashboard/recap'
    | '/dashboard/roles'
    | '/dashboard/sales'
    | '/dashboard/tables'
    | '/menu/$restaurantId/$tableNumber'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cashier'
    | '/kitchen'
    | '/dashboard/appearance'
    | '/dashboard/assistance'
    | '/dashboard/daily-report'
    | '/dashboard/info'
    | '/dashboard/menu'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/orders-stats'
    | '/dashboard/password'
    | '/dashboard/profile'
    | '/dashboard/recap'
    | '/dashboard/roles'
    | '/dashboard/sales'
    | '/dashboard/tables'
    | '/menu/$restaurantId/$tableNumber'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cashier'
    | '/_authenticated/dashboard'
    | '/_authenticated/kitchen'
    | '/_authenticated/dashboard/appearance'
    | '/_authenticated/dashboard/assistance'
    | '/_authenticated/dashboard/daily-report'
    | '/_authenticated/dashboard/info'
    | '/_authenticated/dashboard/menu'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/orders-stats'
    | '/_authenticated/dashboard/password'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/recap'
    | '/_authenticated/dashboard/roles'
    | '/_authenticated/dashboard/sales'
    | '/_authenticated/dashboard/tables'
    | '/menu/$restaurantId/$tableNumber'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MenuRestaurantIdTableNumberRoute: typeof MenuRestaurantIdTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashier': {
      id: '/_authenticated/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthenticatedCashierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/menu/$restaurantId/$tableNumber': {
      id: '/menu/$restaurantId/$tableNumber'
      path: '/menu/$restaurantId/$tableNumber'
      fullPath: '/menu/$restaurantId/$tableNumber'
      preLoaderRoute: typeof MenuRestaurantIdTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/tables': {
      id: '/_authenticated/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof AuthenticatedDashboardTablesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sales': {
      id: '/_authenticated/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof AuthenticatedDashboardSalesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/roles': {
      id: '/_authenticated/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof AuthenticatedDashboardRolesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/recap': {
      id: '/_authenticated/dashboard/recap'
      path: '/recap'
      fullPath: '/dashboard/recap'
      preLoaderRoute: typeof AuthenticatedDashboardRecapRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/password': {
      id: '/_authenticated/dashboard/password'
      path: '/password'
      fullPath: '/dashboard/password'
      preLoaderRoute: typeof AuthenticatedDashboardPasswordRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders-stats': {
      id: '/_authenticated/dashboard/orders-stats'
      path: '/orders-stats'
      fullPath: '/dashboard/orders-stats'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersStatsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/menu': {
      id: '/_authenticated/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthenticatedDashboardMenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/info': {
      id: '/_authenticated/dashboard/info'
      path: '/info'
      fullPath: '/dashboard/info'
      preLoaderRoute: typeof AuthenticatedDashboardInfoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/daily-report': {
      id: '/_authenticated/dashboard/daily-report'
      path: '/daily-report'
      fullPath: '/dashboard/daily-report'
      preLoaderRoute: typeof AuthenticatedDashboardDailyReportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assistance': {
      id: '/_authenticated/dashboard/assistance'
      path: '/assistance'
      fullPath: '/dashboard/assistance'
      preLoaderRoute: typeof AuthenticatedDashboardAssistanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/appearance': {
      id: '/_authenticated/dashboard/appearance'
      path: '/appearance'
      fullPath: '/dashboard/appearance'
      preLoaderRoute: typeof AuthenticatedDashboardAppearanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAppearanceRoute: typeof AuthenticatedDashboardAppearanceRoute
  AuthenticatedDashboardAssistanceRoute: typeof AuthenticatedDashboardAssistanceRoute
  AuthenticatedDashboardDailyReportRoute: typeof AuthenticatedDashboardDailyReportRoute
  AuthenticatedDashboardInfoRoute: typeof AuthenticatedDashboardInfoRoute
  AuthenticatedDashboardMenuRoute: typeof AuthenticatedDashboardMenuRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardOrdersStatsRoute: typeof AuthenticatedDashboardOrdersStatsRoute
  AuthenticatedDashboardPasswordRoute: typeof AuthenticatedDashboardPasswordRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRecapRoute: typeof AuthenticatedDashboardRecapRoute
  AuthenticatedDashboardRolesRoute: typeof AuthenticatedDashboardRolesRoute
  AuthenticatedDashboardSalesRoute: typeof AuthenticatedDashboardSalesRoute
  AuthenticatedDashboardTablesRoute: typeof AuthenticatedDashboardTablesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAppearanceRoute:
      AuthenticatedDashboardAppearanceRoute,
    AuthenticatedDashboardAssistanceRoute:
      AuthenticatedDashboardAssistanceRoute,
    AuthenticatedDashboardDailyReportRoute:
      AuthenticatedDashboardDailyReportRoute,
    AuthenticatedDashboardInfoRoute: AuthenticatedDashboardInfoRoute,
    AuthenticatedDashboardMenuRoute: AuthenticatedDashboardMenuRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardOrdersStatsRoute:
      AuthenticatedDashboardOrdersStatsRoute,
    AuthenticatedDashboardPasswordRoute: AuthenticatedDashboardPasswordRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardRecapRoute: AuthenticatedDashboardRecapRoute,
    AuthenticatedDashboardRolesRoute: AuthenticatedDashboardRolesRoute,
    AuthenticatedDashboardSalesRoute: AuthenticatedDashboardSalesRoute,
    AuthenticatedDashboardTablesRoute: AuthenticatedDashboardTablesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashierRoute: typeof AuthenticatedCashierRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashierRoute: AuthenticatedCashierRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MenuRestaurantIdTableNumberRoute: MenuRestaurantIdTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
